language: node_js
node_js:
- '4.1'
before_deploy:
- git config user.email "njenan@gmail.com"
- git config user.name "Travis CI"
- npm version patch
deploy:
  provider: npm
  email: njenan@gmail.com
  api_key:
    secure: fMyXcwfVnmJzZL3Q9Yw17mgpQX1MCTNEzLkwJ4GTDGXz2IEWsGpDagXstkvjj8XSNUBoeHQZ3SDLx6L1DQ+ii6IgFR8vxe6C17fuYikLM+RX90VU5lxKmubyIlqnqM83eqIxHC+uics/TAPJdcGwZ5gptpUBHzDH58oU9B7GdM4pYFKGhqGQxsGvR57Tp3xEs97+NBa2uUwHxsk48m5zp8hdxy+Th4EsYHELwi6jLJHWEGcrHaAmA+mguxJmGeg10WQAsZm29awEmHiufMlN6x18wDjcKAFRnH/p3rsb+p7XcaUQ1IqUqiFk8jNNSNQm4XEOJ1ChFwLCdlmoB/JpOOjN8ytUyB6TRL3/MsC86hQV9U6z1E7Hx79mRXq2p0xucQMCb972KMnsJDzZkXf0v6d/eGkQY+FK/8t9+EbLBN5Amn9X9KcCsvXB6TTJJ+8RCfqSrNOYCDNuq0cDQQVCwQJ8hxd8gkuk+1tUOUUsV+0o7TzoMSQK9HfF2/BrVaMV9TDPoPhlnq7ndBOVcdXLXfZF5fASwR8VMCMUB0O5tYy45fSGgiocfmssm7VNQzEppeGTifII2dSKFbOjzgZZZHs+AqMYA/AKd/wIV659vtWl84J7nzcAp1yvHa0s6ExoDSJO+WGOuGYVva5r2D57mKCjDu5FIe86f3bisYkRoRA=
  on:
    repo: njenan/Razorback
after_deploy:
- git push --repo https://$USERNAME:$PASSWORD@bitbucket.org/name/repo.git
env:
  global:
  - secure: QEu6VRIhgXbs7bcFnEPU5Tm/LgRwK60W5e7hhn5k8HsnkyOytD7nvgD1H0WcPLA5WxwmYjkP7OCbznhn8EG7/QRA+ZU9b0olNsdDls7qBGyM9CCYNhknN7hbomM0AS9yaxLJ6dPscT9z/MNS+A+AoLQaKdERmV1hfEcvegUXqEq6rfolPyEeehNV3t0eJNBL8x+Jw4tLCplKuT521QmZ1aEgGwmVChEeNzLAxG3gAxEuTjFQUycE62rkEvRDsXMzxrS8c/Hka/7W07dfjLUaI7gpqNoKEKwdH2oGGTTTgAxYfNjggsXy5Ep2Ui+6N2TxDue6izz9Aud9K3R8P7qoAJ3HmjI0QBP8KqrH5Jh1QRnZqrsNno56GfKlikTbwskDY/OtY+tW9nLUF23f+mLjmlIABzzWJcP9NuhhF+6NhdGJ65j3mQeP3Or60RJCAWT3b0hvuzOT2CSqsWz+0g8s5c2ap5FuqyOVgvQtAO28AnPU8ukYocE/dxpp++IY7l3Nk/rv7AS1HAdGbvVSVp0Jxtub6+PrB3A3v2n/mG7FknCyxWzI8OOmq9SrXHA8qNsDeW7D1FmPXlmNp2Vzv7iIi+5LODuA1t53G5w+rFBQgifdyF6HF6GWEd/hN0G2jZ/zKOA6Qt3SywoY8Z1HJo6VSJ9nYfjs5kB1mGb3z6LJoVM=
  - secure: N82i308ACAIuoKsPUz8Vu8O/LnJ1QNgxf35R+UJ4W1+n0GfsijGhDjI/QlVhxA7NIaS0Gc7THHcuQLgPbzkfBDVEzDDpphjFV4l8EXCRqY+HSg8bsTdsVa7SGZFPtbY2VUYNnzEA1tuBkIkNzjMukJ9HOXxIkoKaDIrGI3uweKL/kw0IO4XZwo/nFWFtm0xl3HBOdr+mRZBMJTVjGRjLUq3/M/927xETmw+1Y8+VI2ia/9J6DA/UqyOasgTJlUkC52swxzu2geSufWTHyUB0mEE2SvvS74Zx3sJD2kwbD2PbEY2245LBDicaPuIT62ILSD7am8qtW9ur3fV4FGSqWp4zDoxHEkJ2cIizXuuqBldXe/8LMrad/st+AZD3dH0jbjiqdToX5RE/9piUmpvmzFf9ICU1uTXbJaDgnTX/c/II4I9ebPVjgrmXnovHauPseaN+uayWY/xzYNM3w0vntLtBKEhEh2ERh+ILwfyQtw3lH/hJ9Shv0tjw8uTwggtdSzteFi5vdxVBMj/ivsPMa4kglNMMrIbZVyEtYBe9L01BJ0wZI6TX2EEkeXccjyA6u8ZITOKFuJAuFPd1HDAi13OaMyotGb7m3j73pj+qXoVZPURqPaHeOg9s2xccnXKpDBZHVVL++UPED0HVuBlT59zrCzAZT/1o5lAV96dB1kY=
